### ISSUE TITLE
GroceriesPlus Homepage Navigate to BasketPage

### ISSUE THREAD

**Issue by raptlydev** [TeamRaptly/parashurama#3]
As a user when I am on GroceriesPlus Homepage, i should be able to navigate to BasketPage, so I can see list of products in my ShoppingList

Scenario	Navigate BasketPage
GIVEN 	I am a anonymous/signed in GroceriesPlus customer
WHEN	I open GroceriesPlus app
THEN	I should see navigation option as "CartIcon" in the header to go to BasketPage

**Comment by raptlydev** [comment]
Comments - Mahesh
This is more of a homepage scenario and doesnot cover navigation to shopping list and seeing list of products

**Comment by vishwasc20** [comment]
:+1: LGTM , but probably want to change the `TAB` to button or link?

**Comment by raptlydev** [comment]
Duplicate
